Avoid strncat string overflow warning
Previously got an error about string overflow due to strncat usage

error: ‘__builtin___strncat_chk’ specified bound depends on the
length of the source argument [-Werror=stringop-overflow=]

Replace strncat with snprintf to remove the error